export const metadata = { title: "Sandbox App" };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "ui-sans-serif, system-ui", margin: 0, background: "#0b0d12", color: "#e8ecff" }}>
        <div style={{ maxWidth: 1100, margin: "0 auto", padding: 24 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }}>
            <div style={{ fontWeight: 700, letterSpacing: 0.2 }}>Sandbox App</div>
            <div style={{ opacity: 0.8, fontSize: 13 }}>Generated by Devassist</div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
